[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
version = "18.32.39"
excluded-patches = "always-autorepeat comments enable-tablet-layout hide-autoplay-button tablet-mini-player theme vanced-microg-support"

