[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
apkmirror-arch = "arm-v7a"
build-mode = "module"
version = "latest"
excluded-patches = "always-autorepeat comments copy-video-url premium-heading tablet-mini-player theme vanced-microg-support"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
apkmirror-arch = "arm-v7a"
build-mode = "module"

